### PR TITLE
Workaround to support gazebo and ROS arguments in the command line

### LINKED ISSUE #387: Support to use gazebo and ROS parameters when using rosrun
If I try to run `gzserver` from a roslaunch file, e.g. like this:

```
<node name="gzserver" pkg="gazebo_ros" type="gzserver" />
```

`gzserver` crashes with 

```
[DEBUG]: remap: __name => gzserver
[DEBUG]: Adding tcp socket [11] to pollset
[DEBUG]: UDPROS server listening on port [58980]
[DEBUG]: Publisher update for [/clock]:  already have these connections: 
[DEBUG]: Started node [/gzserver], pid [30771], bound on [peci1-Latitude-E6540], xmlrpc port [40902], tcpros port [60227], using [sim] time
[ INFO]: Finished loading Gazebo ROS API Plugin.
[DEBUG]: XML-RPC call [lookupService] returned an error (-1): [no provider]
[ INFO]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[DEBUG]: Accepted connection on socket [11], new socket [14]
[DEBUG]: Adding tcp socket [14] to pollset
[DEBUG]: TCPROS received a connection from [127.0.0.1:45466]
[DEBUG]: Connection: Creating TransportSubscriberLink for topic [/rosout] connected to [callerid=[/rosout] address=[TCPROS connection on port 60227 to [127.0.0.1:45466 on socket 14]]]
[DEBUG]: shutting down due to exit() or end of main() without cleanup of all NodeHandles
gzserver: /usr/include/boost/thread/pthread/recursive_mutex.hpp:101: boost::recursive_mutex::~recursive_mutex(): Assertion `!pthread_mutex_destroy(&m)' failed.
Aborted (core dumped)
```

I found out it is because of the `__name` and `__log` ROS parameters passed to `rosrun`. The commandline parameters actually are:

```
__name:=gzserver __log:=notimportant -s path/devel/lib/libgazebo_ros_paths_plugin.so -s path/devel/lib/libgazebo_ros_api_plugin.so
```

And I've found out that `gzserver` doesn't like the ROS arguments on its commandline (nor does `rosrun` remove them, which I'd expect).

I propose to patch the `gzserver`, `gzclient` and `gazebo` scripts by adding a line like:

```
final=`echo "$final" | sed 's/__[^ ]*:=[^ ]* \?//g'`
```

which would remove all ROS remapping arguments from the commandline. Or would it be better to remove all ROS argument mappings, just for case someone passes some params?

Or is this whole case just a misconfiguration of my computer? Could you please test with e.g.

```
rosrun gazebo_ros gzserver __name:=gzserver
```

### PR DESCRIPTION
**Pull request by j-rivero**
Reorder command line arguments to place ROS remappings at the end so gazebo passed them to be handle by gazebo ROS plugins. While this is not the recommended way of using rosrun, it could be useful for
some use cases.

Should fix #387

### CODE REVIEW

**Comment by peci1** [comment]
The changes in CMakeLists seem to contain lots of whitespace changes. Are these intentional?

File: gazebo_ros/scripts/libcommon.sh [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+# the function relocate all the remappings in the command at the end of the string
+# this allows some punky uses of rosrun, for more information see:
+# https://github.com/ros-simulation/gazebo_ros_pkgs/issues/387
+relocate_remappings()
+{
+  command_line=${1}
+  
+  for w in $command_line; do
+    if $(echo $w | grep ':='> /dev/null); then
```
Comment (peci1) [inline gazebo_ros/scripts/libcommon.sh]: What about `grep -q ':='` instead of `grep ':=' > /dev/null`?

**Comment by peci1** [comment]
I've tested my use case with remapping before the world file and it works correctly: Gazebo loads the intended world file and ROS receives the remappings.

File: gazebo_ros/scripts/libcommon.sh [hunk 2]
```diff
@@ -0,0 +1,19 @@
+#!/bin/sh
+
+# the function relocate all the remappings in the command at the end of the string
```
Comment (peci1) [inline gazebo_ros/scripts/libcommon.sh]: "the function relocate" => "the function relocates"
"all the remappings" => "all the ROS remappings"

File: gazebo_ros/scripts/libcommon.sh (hunk 1 above)
Comment (j-rivero) [reply gazebo_ros/scripts/libcommon.sh]: better, c1681bc009d94cec96bf173adfd2a3d2510c7e5e

File: gazebo_ros/scripts/libcommon.sh (hunk 2 above)
Comment (j-rivero) [reply gazebo_ros/scripts/libcommon.sh]: fixed c1681bc009d94cec96bf173adfd2a3d2510c7e5e

**Comment by jonbinney** [comment]
I tested on the simulated launchfile that I use for my robot, and it works for me!

**Comment by j-rivero** [comment]
Perfect. Thanks very much for all the ideas and feedback. Let's merge and release. It will take until the next sync to bump to the stable repository.
