### PR TITLE
Set default namespace to model name if <namespace> is not specified

### LINKED ISSUE #1320: Gazebo plugins default to root namespace if <ros><namespace> is not specified
When robots are spawned, e.g. by inserting the models through the GUI, the plugin topics occupy the root (`/`) namespace if the `<ros><namespace>` is unspecified. This causes problems when trying to insert multiple robot models with the same SDF / URDF. The topics will all conflict. 

The change to use the root namespace was introduced in this PR to fix tests due to exceptions: https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1130

It seem like the more desirable behavior is to default the namespace to the parent model name if `<ros><namespace>` unspecified, which is then [consistent with ros1](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/noetic-devel/gazebo_plugins/include/gazebo_plugins/gazebo_ros_utils.h#L132-L139).

### PR DESCRIPTION
**Pull request by iche033**
Signed-off-by: Ian Chen <ichen@osrfoundation.org>

Currently the namespace for gazebo_plugins defaults to the root namespace (`/`) if the `<ros><namespace>` SDF element is not specified. 

This PR updates the namespace logic to be [consistent with ros1](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/noetic-devel/gazebo_plugins/include/gazebo_plugins/gazebo_ros_utils.h#L132-L139), in which the default namespace becomes the parent robot name if left unspecified. 
 
fixes #1320

### CODE REVIEW

**Review by chapulina — COMMENTED** [review]
The general idea sounds good to me. Just note that this changes the behavior of released plugins, which may break downstream users. Galactic is relatively young though, so it may not impact a lot of people.

Note that there are linter errors on CI.

**Comment by scpeters** [comment]
should we target `ros2` first and then consider back-porting to `galactic`?

**Comment by iche033** [comment]
I added a new param, named `<legacy_namespace>`, that defaults to `true` so that the current behavior of using the `/` namespace is preserved. With this new param, users can now switch to use the parent model name as the new namespace by setting it to `false`. 

Once this gets in, I can create a separate PR porting this fix to `ros2` and set `<legacy_namespace>` to false

**Comment by padhupradheep** [comment]
without looking much into the code, will this also solve the #1301 issue related to the /tf topic ?

**Comment by iche033** [comment]
> without looking much into the code, will this also solve the #1301 issue related to the /tf topic ?

probably not as it looks like the transform broadcaster publishes them to absolute namespace
https://github.com/ros2/geometry2/blob/89852f731710061fbd99d7d812523baac6f59a88/tf2_ros/include/tf2_ros/transform_broadcaster.h#L72-L73

File: gazebo_plugins/src/gazebo_ros_video.cpp [hunk 1]
```diff
@@ -197,7 +197,9 @@ void GazeboRosVideo::Load(
   gazebo::rendering::VisualPtr _parent,
   sdf::ElementPtr _sdf)
 {
-  impl_->rosnode_ = gazebo_ros::Node::Get(_sdf);
+  impl_->rosnode_ = gazebo_ros::Node::Get(
+    _sdf,
+    _parent->GetRootVisual()->Name());
```
Comment (chapulina) [inline gazebo_plugins/src/gazebo_ros_video.cpp]: Just curious, why not add a `Get` overload that takes in `VisualPtr`, like it was done for models and sensors?

File: gazebo_ros/include/gazebo_ros/node.hpp [hunk 2]
```diff
@@ -66,6 +69,10 @@ class GAZEBO_ROS_NODE_PUBLIC Node : public rclcpp::Node
    *   <ros>
    *    <!-- Namespace of the node -->
    *    <namespace>/my_ns</namespace>
+   *    <!-- Legacy namespace behavior. True to default to the root namespace
+   *         if <namespace> is not specified, otherwise false to default
+   *         namespace to the the model name -->
```
Comment (chapulina) [inline gazebo_ros/include/gazebo_ros/node.hpp:75]: Maybe mention that it defaults to true if `legacy_namespace` isn't set?

**Review by chapulina — APPROVED** [review]
LGTM now that it's an opt-in feature

File: gazebo_ros/include/gazebo_ros/node.hpp (hunk 2 above)
Comment (scpeters) [reply gazebo_ros/include/gazebo_ros/node.hpp:75]: suggested rephrasing:

~~~
Legacy behavior for setting namespace when <namespace> is not specified.
When <legacy_namespace> is unspecified or set to true, the root namespace `/` is the default.
When <legacy_namespace> is set to false, the default namespace is the model name.
~~~

Comment (iche033) [reply gazebo_ros/include/gazebo_ros/node.hpp:75]: done, updated doc. f24ac84

File: gazebo_plugins/src/gazebo_ros_video.cpp (hunk 1 above)
Comment (iche033) [reply gazebo_plugins/src/gazebo_ros_video.cpp]: yeah that works. It wasn't done in the ros1 version so I also didn't add an overload for it before. I just added it. f24ac84
